version: 2
updates:
  - package-ecosystem: "npm"        # use "npm" even for pnpm projects
    directory: "/"                  # location of package.json / pnpm-lock.yaml
    schedule:
      interval: "weekly"
    assignees:                      # key must be 'assignees' (plural)
      - "techy4shri"
      - "dependabot"
    commit-message:
      prefix: "deps"                # must be an object, not a string
      include: "scope"              # optional: shows package name in commit title
